[Base]
ValueType=UInt8
DistCalcMethod=L2
IndexAlgoType=BKT
Dim=128
VectorPath=xxx/sift1m_base.u8bin
VectorType=DEFAULT
QueryPath=xxx/query.public.10K.u8bin
QueryType=DEFAULT
; WarmupPath=xxx/query.public.10K.u8bin
WarmupType=DEFAULT
TruthPath=xxx/sift_data/bigann-1M
TruthType=XVEC
IndexDirectory=sift1m-u8bin-r8
SSDIndexFileNum=1
N_DATA=1000000

[SelectHead]
isExecute=false
TreeNumber=1
BKTKmeansK=32
BKTLeafSize=8
SamplesNumber=1000
SaveBKT=false
SelectThreshold=10
SplitFactor=6
SplitThreshold=25
Ratio=0.12
NumberOfThreads=150
BKTLambdaFactor=1.0

[BuildHead]
isExecute=false
NeighborhoodSize=32
TPTNumber=32
TPTLeafSize=2000
MaxCheck=16324
MaxCheckForRefineGraph=16324
RefineIterations=3
NumberOfThreads=150
HashTableExponent=4

[BuildSSDIndex]
isExecute=true
BuildSsdIndex=false
InternalResultNum=64
ReplicaCount=8
PostingPageLimit=3
MaxCheck=16324
TmpDir=/tmp/
SearchPostingPageLimit=3
MaxDistRatio=8.0
OutputEmptyReplicaID=true
HashTableExponent=4

; modify configs below to adjust search performance
NumberOfThreads=200
ResultNum=10
SearchInternalResultNum=32
SearchPruning=false

[SearchSSDIndex]
isExecute=true

[SeperatedIndex]
; Sync, Callback or Async
RPCMethod=Callback
; Replication or LoadBalance
RPCWay=LoadBalance
; for server
port=7077
; for client
ServerAddrList=localhost:7077,localhost:8088,localhost:9099


[RedundancyMerger]
MergerInfoFromFile=false
MergerLoadBatchSize=200

; for
NumMachine=3
LoadMergerResult=true
MachineID=0~NumMachine-1, e.g. 2

SavePath=merger-result-sift1m-u8bin
RecoveryPath=recovery-sift1m-u8bin
IndexFileNameFormat=machine-%u-index.bin
PatchFileNameFormat=machine-%u-patch.bin

; for all method, check:
; - AnnService/inc/Helper/StringConvert.h (ExtraFullGraphSearcher<ValueType>::LoadAndRecovery)
; - AnnService/src/Core/SPANN/ExtraFullGraphSearcher.cpp (ConvertStringTo<SPMerge::RecoveryMethod>)
RecoveryMethod=ConcurrentRecovery

; only ScanWrite use it
RecoveryThreads=16
NumVecBuffers=0
; only ConcurrentRecovery use it
NumLoadBuffers=200
ReaderThreads=50
WriterThreads=50
